name: Build and Deploy to Cloud Run

on:
  push:
    branches: [ "master" ]

env:
  PROJECT_ID: janck112 # TODO: update Google Cloud project id
  GAR_LOCATION: asia-southeast2 # TODO: update Artifact Registry location
  SERVICE: tescicd # TODO: update Cloud Run service name
  REGION: asia-southeast2 # TODO: update Cloud Run service region

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}
          export_default_credentials: true

      - name: Configure Docker to use Artifact Registry
        run: gcloud auth configure-docker ${GAR_LOCATION}-docker.pkg.dev

      - name: Build and Push Container
        run: |
          docker build -t ${GAR_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${SERVICE}:${{ github.sha }} ./
          docker push ${GAR_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${SERVICE}:${{ github.sha }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${SERVICE} \
            --image=${GAR_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${SERVICE}:${{ github.sha }} \
            --region=${REGION} \
            --platform=managed \
            --allow-unauthenticated
